# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year-:month-:day-:title/

# Setup
title:            OliverPearmain.com
tagline:          Freelance iOS Developer
url:              http://www.oliverpearmain.com
description:      'Freelance Developer'
baseurl:          /

author:
  name:           Oliver Pearmain
  url:            http://www.oliverpearmain.com

paginate:         5


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OliverPearmain/oliverpearmain.github.io






# The below is required in order to support redirects (see the following URLs for details):
#   https://help.github.com/articles/redirects-on-github-pages/
#   https://help.github.com/articles/using-jekyll-plugins-with-github-pages/
gems:
- jekyll-redirect-from