# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            OliverPearmain.com
tagline:          Freelance iOS Developer
url:              http://oliverpearmain.com
paginate:         1
baseurl:          /
author:
  name:           Oliver Pearmain
  url:            http://oliverpearmain.com
  email:          oliverpearmain@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/OliverPearmain/oliverpearmain.github.io
