# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            OliverPearmain.com
tagline:          Freelance iOS Developer
url:              http://oliverpearmain.com
baseurl:          /
author:
  name:           Oliver Pearmain
  url:            http://oliverpearmain.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/OliverPearmain/oliverpearmain.github.io
